@host = http://localhost:3000

POST {{host}}/ticket/c16b0637-b1b3-4dd5-9ecc-0e5ac5fbc490/open-ticket
Content-Type: application/json

{
  "ticketId": "c16b0637-b1b3-4dd5-9ecc-0e5ac5fbc490",
  "productId": "c16b0637-b1b3-4dd5-9ecc-0e5ac5fbc490",
  "supportCategoryId": "c16b0637-b1b3-4dd5-9ecc-0e5ac5fbc490",
  "priority": "Low",
  "userId": "c16b0637-b1b3-4dd5-9ecc-0e5ac5fbc490",
  "title": "my title",
  "message": "my message"
}

###

GET {{host}}/ticket/c16b0637-b1b3-4dd5-9ecc-0e5ac5fbc490

###

GET {{host}}/tickets?ids=c16b0637-b1b3-4dd5-9ecc-0e5ac5fbc490